# Data Description

- Background: 2026 年 9 月的日期表。用訂單日期連接星期與平日／週末資訊；週末只指星期六、日，沒有另外標記國定假日。 資料由 [生成程式](../code/demo_generate_orders.py) 建立，用來練習多表合併。
- date received: 20261013（產生日期）
- Path to data file: 執行 `python data/code/demo_generate_orders.py` 後產生，沒有外部下載來源。
- Unit of observation: 一天。
- Sample period: 2026-09-01 至 2026-09-30。
- Known issues: 日期沒有重複或缺漏；週末只包含星期六、日。
- Definition for each variable:
    - `order_date`：日期，格式 YYYY-MM-DD。
    - `weekday`：星期一至星期日。
    - `day_type`：平日或週末。
- Data path: [data/raw/demo_calendar.csv](demo_calendar.csv)
- Next processing notebook: [demo_orders_processing.ipynb](../code/demo_orders_processing.ipynb)

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

# 找到專案資料夾，從不同位置開啟 notebook 都能讀到資料。
project_root = Path.cwd().resolve()
while not ((project_root / "AGENTS.md").is_file() and (project_root / "templates").is_dir()):
    if project_root == project_root.parent:
        raise FileNotFoundError("請從專案資料夾內開啟 notebook。")
    project_root = project_root.parent

## Change for Your Own Data

這裡設定要讀取的 CSV。之後換資料時，修改下方檔案路徑，再確認欄位名稱與內容。

In [2]:
data_path = project_root / "data/raw/demo_calendar.csv"

## Summary

先確認欄位、筆數與合併鍵，再看資料的內容。

In [3]:
df = pd.read_csv(data_path)
assert df["order_date"].is_unique, "日期有重複。"
assert not df.isna().any().any()
dates = pd.to_datetime(df["order_date"])
assert dates.equals(pd.Series(pd.date_range("2026-09-01", "2026-09-30")))
assert df["day_type"].eq("週末").equals(dates.dt.dayofweek.ge(5))
print(f"共有 {len(df)} 天，涵蓋 9 月全月。")

共有 30 天，涵蓋 9 月全月。

### Sample

以下最多列出前 10 筆紀錄。

In [4]:
df.head(10)

   order_date weekday day_type
0  2026-09-01     星期二       平日
1  2026-09-02     星期三       平日
2  2026-09-03     星期四       平日
3  2026-09-04     星期五       平日
4  2026-09-05     星期六       週末
5  2026-09-06     星期日       週末
6  2026-09-07     星期一       平日
7  2026-09-08     星期二       平日
8  2026-09-09     星期三       平日
9  2026-09-10     星期四       平日

### Summary Stats

這份表的欄位都是類別或日期文字；摘要用來確認不同值的數量及出現次數。

In [5]:
print(f"原始資料摘要（N={len(df)}；count 為非缺值筆數）")
display(df.describe(include="all"))

column_info = pd.DataFrame({
    "型態": df.dtypes.astype(str),
    "缺值數": df.isna().sum(),
})
print("欄位型態與缺值數")
display(column_info)

原始資料摘要（N=30；count 為非缺值筆數）

        order_date weekday day_type
count           30      30       30
unique          30       7        2
top     2026-09-01     星期二       平日
freq             1       5       22

欄位型態與缺值數

                型態  缺值數
order_date  object    0
weekday     object    0
day_type    object    0